from typing import Protocol, Self

from .contracts import BrokerMessageRequest


class MessageProducerProtocol(Protocol):
    async def publish_message(
        self,
        message: BrokerMessageRequest,
        key: str | None = None,
        topic: str | None = None,
    ) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc_val, exc_tb): ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...


class MessageConsumerProtocol(Protocol):
    async def consume_message(self): ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
