from typing import Protocol
from uuid import UUID

from app.application.dto import (InboxDTO, InboxDTOResponse, OrderDTO,
                                 OrderDTOResponse, OrderStatusDTO, OutboxDTO,
                                 OutboxDTOResponse)
from app.application.enums.events import (EventTypeEnum, InboxEventStatusEnum,
                                          OutboxEventStatusEnum)


class OrderRepositoryProtocol(Protocol):
    async def create(self, entity: OrderDTO) -> OrderDTOResponse: ...
    async def get_by_id(self, entity_id: UUID) -> OrderDTOResponse | None: ...
    async def get_order(self, idempotency_key: UUID) -> OrderDTOResponse | None: ...
    async def update(self, entity: OrderDTO, order_id: UUID) -> OrderDTO | None: ...
    async def delete(self, entity_id: UUID) -> None: ...


class OutboxRepositoryProtocol(Protocol):
    async def create(self, entity: OutboxDTO) -> None: ...
    async def get_events(
        self,
        event_type: EventTypeEnum | None,
        status: OutboxEventStatusEnum | None,
        limit: int | None = 100,
    ) -> list[OutboxDTOResponse] | list[None]: ...
    async def mark_as_sent(self, event_id: UUID) -> None: ...
    async def get_unsent_notifications(
        self,
    ) -> list[OutboxDTOResponse] | list[None]: ...


class InboxRepositoryProtocol(Protocol):
    async def create(self, entity: InboxDTO) -> None: ...
    async def get_events(
        self,
        event_type: EventTypeEnum | None = None,
        status: InboxEventStatusEnum | None = None,
        limit: int | None = 100,
    ) -> list[InboxDTOResponse]: ...
    async def get_event(self, idempotency_key: UUID) -> InboxDTOResponse | None: ...
    async def mark_as_processed(self, event_id: UUID) -> None: ...


class OrderStatusRepositoryProtocol(Protocol):
    async def create(self, entity: OrderStatusDTO) -> OrderStatusDTO: ...
