from typing import Protocol
from uuid import UUID
from app.application.dto.order import OrderDTO, OrderStatusDTO, OrderDTOResponse
from app.application.dto.outbox import OutboxDTO, OutboxDTOResponse
from app.application.dto.inbox import InboxDTO, InboxDTOResponse
from app.application.dto.notification import NotificationDTO, NotificationDTOResponse
from ..enums.events import OutboxEventStatusEnum, EventTypeEnum, InboxEventStatusEnum


class OrderRepositoryProtocol(Protocol):
    async def create(self, entity: OrderDTO) -> OrderDTOResponse: ...
    async def get_by_id(self, entity_id: UUID) -> OrderDTO | None: ...
    async def get_order(self, idempotency_key: UUID) -> OrderDTOResponse | None: ...
    async def update(self, entity: OrderDTO, order_id: UUID) -> OrderDTO | None: ...
    async def delete(self, entity_id: UUID) -> None: ...


class OutboxRepositoryProtocol(Protocol):
    async def create(self, entity: OutboxDTO) -> None: ...
    async def get_events(
        self,
        event_type: EventTypeEnum | None,
        status: OutboxEventStatusEnum | None,
        limit: int | None = 100,
    ) -> list[OutboxDTOResponse]: ...
    async def mark_as_sent(self, event_id: UUID) -> None: ...


class InboxRepositoryProtocol(Protocol):
    async def create(self, entity: InboxDTO) -> None: ...
    async def get_events(
        self,
        event_type: EventTypeEnum | None = None,
        status: InboxEventStatusEnum | None = None,
        limit: int | None = 100,
    ) -> list[InboxDTOResponse]: ...
    async def get_event(self, idempotency_key: UUID) -> InboxDTOResponse | None: ...
    async def mark_as_processed(self, event_id: UUID) -> None: ...


class OrderStatusRepositoryProtocol(Protocol):
    async def create(self, entity: OrderStatusDTO) -> OrderStatusDTO: ...


class NotificationRepositoryProtocol(Protocol):
    async def create(self, entity: NotificationDTO) -> None: ...
    async def get_notifications(self) -> list[NotificationDTOResponse]: ...
    async def mark_as_sent(self, notification_id: UUID) -> None: ...
