from dishka import make_async_container

from .providers import (ApplicationSettingsProvider,
                        AppNotificationsServiceProvider,
                        AppPaymentsServiceProvider, CatalogServiceProvider,
                        CreateOrderUseCaseProvider,
                        CreatePaymentUseCaseProvider, DatabaseProvider,
                        DatabaseSessionProvider,
                        HandlePaymentResponseUseCaseProvider,
                        HTTPClientProvider, HTTPClientSettingsProvider,
                        InboxWorkerProvider, KafkaConfigProvider,
                        KafkaProducerProvider,
                        OutboxNotificationsWorkerProvider,
                        OutboxPaymentsWorkerProvider,
                        OutboxShippingWorkerProvider, PaymentsServiceProvider,
                        UnitOfWorkProvider, UpdateOrderStatusUseCaseProvider)

container = make_async_container(
    ApplicationSettingsProvider(),
    HTTPClientSettingsProvider(),
    DatabaseProvider(),
    DatabaseSessionProvider(),
    HTTPClientProvider(),
    CatalogServiceProvider(),
    PaymentsServiceProvider(),
    AppPaymentsServiceProvider(),
    AppNotificationsServiceProvider(),
    KafkaConfigProvider(),
    KafkaProducerProvider(),
    UnitOfWorkProvider(),
    CreateOrderUseCaseProvider(),
    CreatePaymentUseCaseProvider(),
    OutboxPaymentsWorkerProvider(),
    HandlePaymentResponseUseCaseProvider(),
    UpdateOrderStatusUseCaseProvider(),
    InboxWorkerProvider(),
    OutboxNotificationsWorkerProvider(),
    OutboxShippingWorkerProvider(),
)
