from dishka import make_async_container
from .providers import (
    ApplicationSettingsProvider,
    HTTPClientSettingsProvider,
    DatabaseProvider,
    DatabaseSessionProvider,
    HTTPClientProvider,
    CatalogServiceProvider,
    CreateOrderUseCaseProvider,
    PaymentsServiceProvider,
    AppPaymentsServiceProvider,
    AppNotificationsServiceProvider,
    UnitOfWorkProvider,
    CreatePaymentUseCaseProvider,
    OutboxPaymentsWorkerProvider,
    HandlePaymentResponseUseCaseProvider,
    UpdateOrderStatusUseCaseProvider,
    InboxWorkerProvider,
    OutboxNotificationsWorkerProvider,
)

container = make_async_container(
    ApplicationSettingsProvider(),
    HTTPClientSettingsProvider(),
    DatabaseProvider(),
    DatabaseSessionProvider(),
    HTTPClientProvider(),
    CatalogServiceProvider(),
    PaymentsServiceProvider(),
    AppPaymentsServiceProvider(),
    AppNotificationsServiceProvider(),
    UnitOfWorkProvider(),
    CreateOrderUseCaseProvider(),
    CreatePaymentUseCaseProvider(),
    OutboxPaymentsWorkerProvider(),
    HandlePaymentResponseUseCaseProvider(),
    UpdateOrderStatusUseCaseProvider(),
    InboxWorkerProvider(),
    OutboxNotificationsWorkerProvider(),
)
