"""Initial migration

Revision ID: f0ecaa8f00a7
Revises:
Create Date: 2026-01-19 20:32:29.474279

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f0ecaa8f00a7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=19, scale=2), nullable=False),
        sa.Column("idempotency_key", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount >= 0", name="positive_amount"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index("idx_item_id", "orders", ["item_id"], unique=False)
    op.create_index("idx_user_id", "orders", ["user_id"], unique=False)
    op.create_table(
        "outbox",
        sa.Column(
            "event_type",
            sa.Enum(
                "ORDER_CREATED",
                "ORDER_PAID",
                "ORDER_CANCELLED",
                "PAYMENT_REQUESTED",
                name="eventtypeenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SENT", name="outboxeventstatusenum"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # sa.CheckConstraint("status IN ('PENDING', 'SENT')", name='valid_outbox_status'),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_event_type_status_type", "outbox", ["event_type", "status"], unique=False
    )
    op.create_index("idx_status", "outbox", ["status"], unique=False)
    op.create_table(
        "order_status",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("NEW", "PAID", "SHIPPED", "CANCELLED", name="orderstatusenum"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # sa.CheckConstraint("status IN ('new', 'paid', 'shipped', 'cancelled')", name='valid_order_status'),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_order_id", "order_status", ["order_id"], unique=False)
    op.create_index(
        "idx_order_id_status", "order_status", ["order_id", "status"], unique=False
    )
    op.create_table(
        "inbox",
        sa.Column(
            "event_type",
            sa.Enum(
                "ORDER_CREATED",
                "ORDER_PAID",
                "ORDER_CANCELLED",
                "PAYMENT_REQUESTED",
                name="eventtypeenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSED", name="inboxeventstatusenum"),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # sa.CheckConstraint("status IN ('pending', 'sent')", name='valid_outbox_status'),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index("idx_status_inbox", "inbox", ["status"], unique=False)
    op.create_table(
        "notifications",
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "sent", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notifications")
    op.drop_index("idx_status", table_name="inbox")
    op.drop_table("inbox")
    op.drop_index("idx_order_id_status", table_name="order_status")
    op.drop_index("idx_order_id", table_name="order_status")
    op.drop_table("order_status")
    op.drop_index("idx_status", table_name="outbox")
    op.drop_index("idx_event_type_status_type", table_name="outbox")
    op.drop_table("outbox")
    op.drop_index("idx_user_id", table_name="orders")
    op.drop_index("idx_item_id", table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
